//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PigeonsTracker.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_ur_PK {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_ur_PK() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PigeonsTracker.Shared.ResourceFiles.Language.ur-PK", typeof(Language_ur_PK).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمام ٹورنامنٹ یا مشقین.
        /// </summary>
        internal static string AllTournaments {
            get {
                return ResourceManager.GetString("AllTournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اورج.
        /// </summary>
        internal static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرندوں کی معلومات.
        /// </summary>
        internal static string BirdsInformation {
            get {
                return ResourceManager.GetString("BirdsInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرندے کا نام.
        /// </summary>
        internal static string BirdsName {
            get {
                return ResourceManager.GetString("BirdsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان تبدیل کریں.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جلد آرہا ہے۔.
        /// </summary>
        internal static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابطہ کریں.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ہم سے رابطہ کریں.
        /// </summary>
        internal static string ContactUsTitle {
            get {
                return ResourceManager.GetString("ContactUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاپی.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ٹورنامنٹ بنائیں.
        /// </summary>
        internal static string CreateTournament {
            get {
                return ResourceManager.GetString("CreateTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ٹریکنگ ریکارڈ بنائیں.
        /// </summary>
        internal static string CreateTrackingRecord {
            get {
                return ResourceManager.GetString("CreateTrackingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ختم.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فلائنگ ڈے ریکارڈ.
        /// </summary>
        internal static string FlyingDayRecord {
            get {
                return ResourceManager.GetString("FlyingDayRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فلائنگ ڈے.
        /// </summary>
        internal static string FlyingStartDate {
            get {
                return ResourceManager.GetString("FlyingStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فلائنگ اسٹارٹ ٹائم.
        /// </summary>
        internal static string FlyingStartTime {
            get {
                return ResourceManager.GetString("FlyingStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to براہ کرم ٹورنامنٹ کا نام فراہم کریں.
        /// </summary>
        internal static string HelpTournamentName {
            get {
                return ResourceManager.GetString("HelpTournamentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ہوم پیج.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کبوتر ٹریکر کی ایپلی کیشن آپ کو ٹورنامنٹ کو اسٹور کرنے یا میچ اسکور کی مشق کرنے میں مدد دیتی ہے اور آپ کو اپنے دوستوں اور گروپس میں مواد کو شیئر کرنے کی اہلیت فراہم کرتی ہے۔.
        /// </summary>
        internal static string InfoPageContextP1 {
            get {
                return ResourceManager.GetString("InfoPageContextP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات.
        /// </summary>
        internal static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یہ ایپ انسٹال کریں؟.
        /// </summary>
        internal static string InstallThisApplication {
            get {
                return ResourceManager.GetString("InstallThisApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اترا.
        /// </summary>
        internal static string Landed {
            get {
                return ResourceManager.GetString("Landed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینڈنگ ٹائم.
        /// </summary>
        internal static string LandingTime {
            get {
                return ResourceManager.GetString("LandingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ہماری نئی ایپ میں خوش آمدید.
        /// </summary>
        internal static string MainPageContent {
            get {
                return ResourceManager.GetString("MainPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اپنے کبوتر کو فالو کریں.
        /// </summary>
        internal static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمبر.
        /// </summary>
        internal static string Nr {
            get {
                return ResourceManager.GetString("Nr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیماریوں اور علاج.
        /// </summary>
        internal static string PigeonsDiseasesAndCure {
            get {
                return ResourceManager.GetString("PigeonsDiseasesAndCure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چھت کا نام.
        /// </summary>
        internal static string RoofName {
            get {
                return ResourceManager.GetString("RoofName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جب آپ اسے استعمال کریں گے تو نقل شدہ متن کی شکل درست ہوگی۔.
        /// </summary>
        internal static string ShareFormatText {
            get {
                return ResourceManager.GetString("ShareFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسٹور کرائیں.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کل اورج.
        /// </summary>
        internal static string TotalAverage {
            get {
                return ResourceManager.GetString("TotalAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کل پرندے.
        /// </summary>
        internal static string TotalBirdsCount {
            get {
                return ResourceManager.GetString("TotalBirdsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کل گھنٹے.
        /// </summary>
        internal static string TotalHours {
            get {
                return ResourceManager.GetString("TotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کل وقت.
        /// </summary>
        internal static string TotalTime {
            get {
                return ResourceManager.GetString("TotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ٹورنامنٹ اختتامی تاریخ.
        /// </summary>
        internal static string TournamentEndDate {
            get {
                return ResourceManager.GetString("TournamentEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ٹورنامنٹ کا نام.
        /// </summary>
        internal static string TournamentName {
            get {
                return ResourceManager.GetString("TournamentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ٹورنامنٹ شروع ہونے کی تاریخ.
        /// </summary>
        internal static string TournamentStartDate {
            get {
                return ResourceManager.GetString("TournamentStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ٹورنامنٹ کی قسم منتخب کریں.
        /// </summary>
        internal static string TournamentType {
            get {
                return ResourceManager.GetString("TournamentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ٹورنامنٹ.
        /// </summary>
        internal static string TournamentType1 {
            get {
                return ResourceManager.GetString("TournamentType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پریکٹس .
        /// </summary>
        internal static string TournamentType2 {
            get {
                return ResourceManager.GetString("TournamentType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ٹریکنگ.
        /// </summary>
        internal static string TrackingTileText {
            get {
                return ResourceManager.GetString("TrackingTileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قسم.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اپ ڈیٹ.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ٹریکنگ ریکارڈ اپ ڈیٹ.
        /// </summary>
        internal static string UpdateTrackingRecord {
            get {
                return ResourceManager.GetString("UpdateTrackingRecord", resourceCulture);
            }
        }
    }
}
