//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PigeonsTracker.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PigeonsTracker.Shared.ResourceFiles.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Tournaments.
        /// </summary>
        internal static string AllTournaments {
            get {
                return ResourceManager.GetString("AllTournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birds Information.
        /// </summary>
        internal static string BirdsInformation {
            get {
                return ResourceManager.GetString("BirdsInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bird Name.
        /// </summary>
        internal static string BirdsName {
            get {
                return ResourceManager.GetString("BirdsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactus.
        /// </summary>
        internal static string ContactUsTitle {
            get {
                return ResourceManager.GetString("ContactUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Tournament.
        /// </summary>
        internal static string CreateTournament {
            get {
                return ResourceManager.GetString("CreateTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Tracking Record.
        /// </summary>
        internal static string CreateTrackingRecord {
            get {
                return ResourceManager.GetString("CreateTrackingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flying Day Record.
        /// </summary>
        internal static string FlyingDayRecord {
            get {
                return ResourceManager.GetString("FlyingDayRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flying Start Day.
        /// </summary>
        internal static string FlyingStartDate {
            get {
                return ResourceManager.GetString("FlyingStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flying Start Time.
        /// </summary>
        internal static string FlyingStartTime {
            get {
                return ResourceManager.GetString("FlyingStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Provide Tournament Name.
        /// </summary>
        internal static string HelpTournamentName {
            get {
                return ResourceManager.GetString("HelpTournamentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PigeonsTracker application helps you store the tournaments or practice match score and provide you the ability to share the content with your friends and in groups..
        /// </summary>
        internal static string InfoPageContextP1 {
            get {
                return ResourceManager.GetString("InfoPageContextP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install this app?.
        /// </summary>
        internal static string InstallThisApplication {
            get {
                return ResourceManager.GetString("InstallThisApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landed.
        /// </summary>
        internal static string Landed {
            get {
                return ResourceManager.GetString("Landed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landing Time.
        /// </summary>
        internal static string LandingTime {
            get {
                return ResourceManager.GetString("LandingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to our new app..
        /// </summary>
        internal static string MainPageContent {
            get {
                return ResourceManager.GetString("MainPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow your pigeon!.
        /// </summary>
        internal static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr..
        /// </summary>
        internal static string Nr {
            get {
                return ResourceManager.GetString("Nr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diseases and Cure.
        /// </summary>
        internal static string PigeonsDiseasesAndCure {
            get {
                return ResourceManager.GetString("PigeonsDiseasesAndCure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loft Name.
        /// </summary>
        internal static string RoofName {
            get {
                return ResourceManager.GetString("RoofName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the copied text will be correct when you will use it..
        /// </summary>
        internal static string ShareFormatText {
            get {
                return ResourceManager.GetString("ShareFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Average.
        /// </summary>
        internal static string TotalAverage {
            get {
                return ResourceManager.GetString("TotalAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Birds.
        /// </summary>
        internal static string TotalBirdsCount {
            get {
                return ResourceManager.GetString("TotalBirdsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hours.
        /// </summary>
        internal static string TotalHours {
            get {
                return ResourceManager.GetString("TotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time.
        /// </summary>
        internal static string TotalTime {
            get {
                return ResourceManager.GetString("TotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament End Date.
        /// </summary>
        internal static string TournamentEndDate {
            get {
                return ResourceManager.GetString("TournamentEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament Name.
        /// </summary>
        internal static string TournamentName {
            get {
                return ResourceManager.GetString("TournamentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament Start Date.
        /// </summary>
        internal static string TournamentStartDate {
            get {
                return ResourceManager.GetString("TournamentStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament Type.
        /// </summary>
        internal static string TournamentType {
            get {
                return ResourceManager.GetString("TournamentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament.
        /// </summary>
        internal static string TournamentType1 {
            get {
                return ResourceManager.GetString("TournamentType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice.
        /// </summary>
        internal static string TournamentType2 {
            get {
                return ResourceManager.GetString("TournamentType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        internal static string TrackingTileText {
            get {
                return ResourceManager.GetString("TrackingTileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Tracking Record.
        /// </summary>
        internal static string UpdateTrackingRecord {
            get {
                return ResourceManager.GetString("UpdateTrackingRecord", resourceCulture);
            }
        }
    }
}
